export default [
    {
        question: "Welche Aussagen treffen bei primitiven Datentypen zu?",
        type: "checkbox",
        answers: [
            "Sie können Gleitkommazahlen 100% genau abbilden",
            "Sie können nur Zahlen abbilden",
            "Sie besitzen eine festgelegte Reichweite an Werten",
        ],
        correctAnswerIndex: [2],
        answer: [],
    },
    {
        question: "Was ist der maximale Wert eines Integers? (32 Bit)",
        type: "radio",
        answers: [
            "2147483647",
            "8388608",
            "32768",
            "Integer haben keinen Wert",
        ],
        correctAnswerIndex: 0,
        answer: [],
    },
    {
        question: "Welcher Datentyp ist passend?: true",
        type: "radio",
        answers: [
            "int",
            "short",
            "String",
            "boolean",
        ],
        correctAnswerIndex: 3,
        answer: [],
    },
    {
        question: "Welcher Datentyp ist KEIN primitiver Datentyp?",
        type: "radio",
        answers: [
            "char",
            "int",
            "String",
            "float",
        ],
        correctAnswerIndex: 2,
        answer: 0,
    },
    {
        question: "Welcher Datentyp ist passend?: -8746127273273",
        type: "radio",
        answers: [
            "byte",
            "short",
            "int",
            "long",
        ],
        correctAnswerIndex: 3,
        answer: [],
    },
    {
        question: "Ein 32-Bit-Integer steht auf 2147483647. Es wird 1 addiert. Was ist das Ergebnis?",
        type: "text",
        correctAnswer: '-2147483648',
        answer: '',
    },
    {
        question: "Der Most Significant Bit ist der..",
        type: "radio",
        answers: [
            "Bit mit dem niedrigsten Stellenwert",
            "Bit mit dem höchsten Stellenwert",
            "extra geflaggte Bit",
        ],
        correctAnswerIndex: 1,
        answer: [],
    },
    {
        question: "Ein anderes Wort für Int16",
        type: "radio",
        answers: [
            "Byte (8 Bit)",
            "Short (16 Bit)",
            "Integer (32 Bit)",
            "Long (64 Bit)",
        ],
        correctAnswerIndex: 1,
        answer: [],
    },
    {
        question: "Wie viele Nachkommastellen Genauigkeit hat ein Float?",
        type: "radio",
        answers: [
            "4",
            "15",
            "unendlich",
            "7",
        ],
        correctAnswerIndex: 3,
        answer: [],
    },
    {
        question: "Wie viele unterschiedliche Zeichen lassen sich mit 1 Byte darstellen?",
        type: "radio",
        answers: [
            "192",
            "255",
            "256",
        ],
        correctAnswerIndex: 2,
        answer: [],
    },
    {
        question: "Welches Zahlensystem verwendet das Computersystem zum Speichern und Bearbeiten von Daten?",
        type: "radio",
        answers: [
            "Dual-/Binärsystem",
            "Oktalsystem",
            "Dezimalsystem",
            "Hexadezimalsystem",
        ],
        correctAnswerIndex: 0,
        answer: [],
    },
    {
        question: "Vervollständige: Bei der Deklaration von Variablen muss immer ein Datentyp mit angegeben werden, um entsprechend Speicher zu...",
        type: "radio",
        answers: [
            "alliieren",
            "allozieren",
            "applaudieren",
        ],
        correctAnswerIndex: 1,
        answer: [],
    },
    {
        question: "Richtig oder falsch: Der Computer macht einen klaren Unterschied zwischen Ganzzahlen und Kommazahlen",
        type: "radio",
        answers: [
            "richtig",
            "falsch",
        ],
        correctAnswerIndex: 0,
        answer: [],
    },
    {
        question: "Wann kann der Prozessor einen Ganzzahlenüberlauf nicht erkennen?",
        type: "radio",
        answers: [
            "Wenn ein Ergebnis den Gültigkeitsbereich des Rechenwerks überschreitet",
            "Wenn man Zweierkomplementzahlen addiert",
            "Wenn eine Variable zu wenig Stellen hat, um den Wert zu speichern",
        ],
        correctAnswerIndex: 2,
        answer: [],
    },
    {
        question: "Was sind alphanumerische Daten? (Mehrere Antworten)",
        type: "checkbox",
        answers: [
            "Text",
            "Bilder",
            "Musik",
            "Sonderzeichen",
            "Zahlen",
        ],
        correctAnswerIndex: [0, 3, 4],
        answer: [],
    },
    {
        question: "Was wird theoretisch im Jahre 2038 passieren?",
        type: "radio",
        answers: [
            "Donald Trump gewinnt Dschungelcamp",
            "Die Unixzeit in gespeichert als 32-Bit Ganzzahl läuft über",
            "Der Zähler des NTP läuft über",
        ],
        correctAnswerIndex: 1,
        answer: [],
    },
    {
        question: "Was ist eine Ganzzahl? (Mehrere Antworten)",
        type: "checkbox",
        answers: [
            "Int32",
            "Int64",
            "Long",
            "Double",
        ],
        correctAnswerIndex: [0, 1, 2],
        answer: [],
    },
]